baseUrl = "https://omnibear.com"
languageCode = "en-US"
paginate = 20
theme = "omnibear"
title = "Omnibear"

googleAnalytics = "UA-37381912-3"

[params]
  intro = "A micropub browser extension"
  description = "Repost, like, or reply to anything online. Omnibear is an integrated Micropub client built into your browser."
  dateFormat = '02 January 2006'

[params.extra]
  copyright = "Built by [Keith J. Grant](https://keithjgrant.com) | View [source on Github](https://github.com/keithjgrant/omnibear)"

[[menu.main]]
  name = "Install"
  weight = 100
  url = "/install"

[[menu.main]]
  name = "Features"
  weight = 200
  url = "/features"

[[menu.main]]
  name = "Changelog"
  weight = 300
  url = "/releases"
