name = "Omnibear"
license = "MIT"
licenselink = "https://github.com/shenoybr/hugo-goa/blob/master/LICENSE.md"
description = "Modified version of the Goa Theme"
homepage = "https://omnibear.com"
tags = ["minimal", "clean"]
features = ["blog", "pages", "minimal", "responsive", "404", "icons", "anlaytics"]
min_version = 0.16

[author]
  name = "Rajesh Shenoy"
  homepage = "https://github.com/shenoybr"
